- hosts: server
  remote_user: ubuntu
  become: true
  tasks:
    - name: Update cache and install packages
      apt:
        name:
          - nginx
          - fail2ban
        update_cache: yes
        state: present
      tags: [nginx, security]
    
    - name: Copy static HTML file
      copy:
        src: ./nginx/index.html
        dest: /var/www/html/
      tags: [nginx]

    - name: Configure fail2ban
      copy:
        content: |
          [DEFAULT]
          ignoreip = 127.0.0.1/8
          bantime  = 600
          findtime  = 600
          maxretry = 5

          [sshd]
          enabled = true
        dest: /etc/fail2ban/fail2ban.conf
      notify: Restart fail2ban
      tags: [security]

    - name: Configure Prometheus
      apt:
        name: prometheus
        update_cache: yes
      notify: Restart Prometheus
      tags: [prometheus]

    - name: Add Grafana APT key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        update_cache: yes

      tags: [grafana]

    - name: Start Grafana Service
      ansible.builtin.service:
        name: grafana-server
        state: started
        enabled: true
      tags: [grafana]

    
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted

    - name: Restart Prometheus
      service:
        name: prometheus
        state: restarted  