name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color

  #   - name: Terraform Apply
  #     run: terraform apply -auto-approve

  # ansible:
  #   runs-on: ubuntu-latest
  #   needs: terraform

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Setup Ansible
  #     run: sudo apt-get update && sudo apt-get install -y ansible

  #   - name: Run Ansible Playbook
  #     env:
  #       ANSIBLE_HOST_KEY_CHECKING: 'false'
  #     run: ansible-playbook -i ansible/hosts.ini ansible/playbook.yml