name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform_and_ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init 

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Make generate_inventory.sh executable
      run: chmod +x generate_inventory.sh

    - name: Generate inventory
      run: ./generate_inventory.sh

    - name: Run Playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml