name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform_and_ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init 

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve

    - name: Get IP from Terraform
      id: terraform_output
      run: echo "INSTANCE_IP=$(terraform output -raw IP)" >> $GITHUB_ENV

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ansible
        key: ${{secrets.SSH_PRIVATE_KEY}}
        inventory: |
          [server]
            ${{ env.INSTANCE_IP }}
